### ISSUE TITLE
Add static analysis tools

### ISSUE THREAD

**Issue by korthout** [telcirion/odin#3]
Some kind of static analysis tools are needed, since different coding styles seem to be used throughout the code, as well as sometimes bugs may be introduced by accident that could've been caught by such tools. Example:
```java
try {
  var x=123;
  var y = true; // different styles can be reduced through checkstyle
} catch(Exception e) {
  e.printStackTrace();
 // exception swallowing is caught by error-prone 
}
```
Possible tools to use:
 - checkstyle
 - pmd
 - spotbugs
 - sonarqube
 - google-errorprone

**Comment by telcirion** [comment]
Done!
